# Generated by Django 3.1.5 on 2021-01-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='field_name',
            field=models.URLField(default=None),
        ),
    ]
