# Generated by Django 3.1.5 on 2021-01-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_auto_20210111_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='weblink',
            field=models.URLField(blank=True),
        ),
    ]
