# Generated by Django 3.1.5 on 2021-01-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_auto_20210111_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='weblink',
        ),
    ]
