# Generated by Django 3.1.5 on 2021-01-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_remove_slider_weblink'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='weblink',
            field=models.URLField(blank=True),
        ),
    ]
